name: Build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o build/go-app.exe -v
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: cryogenetics-logistics-solution
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        enable-oryx-build: false